Fix restore_dimensions not working because we don't have any textures
```js

TypeError: Cannot read property 'height' of undefined
    at restore_dimensions (eval at <anonymous> (eval at Game.init (/home/pi/ALBot/game.js:141:5)), <anonymous>:2450:26)
```